spring.application.name=Kumo

# url
server.port=8080
server.servlet.context-path=/

# log
logging.level.root=info
logging.level.net.datasa.community=debug
logging.level.org.springframework.security=DEBUG

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace

# API Key
kumo.google.maps.keys=${GOOGLE_MAPS_KEY}

# ==========================
# [파일 업로드 설정]
# ==========================
# 1. 파일 크기 제한
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# 2. (중요) 실제 저장할 경로 변수 선언 (이름은 내 맘대로 지음)
# 주의: 끝에 '/'를 꼭 붙여주세요!
file.upload.dir=C:/KumoUpload/

# 🌟 채팅 파일 업로드 경로 추가 (실제 폴더가 위치할 경로로 맞춰주세요!)
file.upload.chat=chat_uploads/

# ==========================================
# 3. 이메일(SMTP) 설정 - Gmail
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# 본인의 지메일 주소
spring.mail.username=${Gmail_id}
# 아까 발급받은 16자리 앱 비밀번호 (공백 없이 입력)
spring.mail.password=${App_Password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# 구글 리캡차 설정
google.recaptcha.site-key=${GOOGLE_RECAPTCHA_SITE_KEY}
google.recaptcha.secret-key=${GOOGLE_RECAPTCHA_SECRET_KEY}

# DeepL
deepl.api.key=${DEEPL_API_KEY}
deepl.api.url=https://api-free.deepl.com/v2/translate






